[global]
   workgroup = WORKGROUP
   server string = JB Gateway Samba Server
   server role = standalone server
   log file = /var/log/samba/log.%m
   max log size = 50
   dns proxy = no
   map to guest = Bad User
   usershare allow guests = yes

[projects]
   path = /home/jb-gateway/projects
   browseable = yes
   read only = no
   guest ok = no
   valid users = jb-gateway
   create mask = 0644
   directory mask = 0755